import { useEffect, useRef, useState, useId } from 'react';
import mermaid from 'mermaid';
import DOMPurify from 'dompurify';

interface ArchitectureDiagramProps {
  chart: string;
  title?: string;
  className?: string;
  preview?: boolean;
  onExpand?: () => void;
}

export function ArchitectureDiagram({ chart, title, className = '', preview = false, onExpand }: ArchitectureDiagramProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svgContent, setSvgContent] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const uniqueId = useId().replace(/:/g, '-');

  useEffect(() => {
    let isMounted = true;

    // Check current theme from document
    const getTheme = () => {
      const isDark = document.documentElement.classList.contains('dark');
      return isDark ? 'dark' : 'base';
    };

    const renderDiagram = async () => {
      setIsLoading(true);
      setError(null);

      try {
        const theme = getTheme();

        // Initialize Mermaid with current theme
        mermaid.initialize({
          startOnLoad: false,
          theme,
          securityLevel: 'loose',
          fontFamily: 'JetBrains Mono, monospace',
        });

        // Use mermaid.render() which doesn't require a visible DOM element
        const diagramId = `mermaid-${uniqueId}-${Date.now()}`;
        const { svg } = await mermaid.render(diagramId, chart);

        // Sanitize SVG to prevent XSS attacks
        const sanitizedSvg = DOMPurify.sanitize(svg, {
          USE_PROFILES: { svg: true, svgFilters: true },
          ADD_TAGS: ['foreignObject'],
        });

        if (isMounted) {
          setSvgContent(sanitizedSvg);
          setIsLoading(false);
        }
      } catch (err) {
        if (isMounted) {
          const errorMessage = err instanceof Error ? err.message : 'Failed to render diagram';
          setError(errorMessage);
          setIsLoading(false);
          console.error('Mermaid rendering error:', err);
        }
      }
    };

    // Watch for theme changes
    const observer = new MutationObserver(() => {
      renderDiagram();
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class'],
    });

    // Initial render
    renderDiagram();

    return () => {
      isMounted = false;
      observer.disconnect();
    };
  }, [chart, uniqueId]);

  // SVG is generated by Mermaid and sanitized with DOMPurify
  const diagramContent = (
    <div className="glass-card-sm p-6 overflow-x-auto relative">
      {isLoading && !error && (
        <div className="absolute inset-0 flex items-center justify-center bg-bg-tertiary rounded-xl">
          <div className="text-text-secondary">Loading diagram...</div>
        </div>
      )}
      {error && (
        <div className="py-12 text-center">
          <div className="text-red-500 font-medium mb-2">Error rendering diagram</div>
          <div className="text-text-tertiary text-sm">{error}</div>
        </div>
      )}
      {svgContent && (
        <div
          ref={containerRef}
          className="opacity-100 transition-opacity duration-300 [&_svg]:max-w-full [&_svg]:h-auto"
          dangerouslySetInnerHTML={{ __html: svgContent }}
        />
      )}
    </div>
  );

  if (preview) {
    return (
      <button
        type="button"
        onClick={onExpand}
        className="w-full text-left group cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-bg-tertiary rounded-xl"
        aria-label="Click to expand architecture diagram"
      >
        <div className="relative h-40 overflow-hidden rounded-xl border border-white/10 hover:border-primary/50 transition-colors">
          {/* Scaled diagram container */}
          <div
            className="origin-top-left pointer-events-none"
            style={{ transform: 'scale(0.35)', width: '285%' }}
          >
            {diagramContent}
          </div>

          {/* Expand overlay */}
          <div className="absolute inset-0 bg-gradient-to-t from-bg-primary/80 to-transparent flex items-end justify-center pb-3 opacity-0 group-hover:opacity-100 transition-opacity">
            <span className="flex items-center gap-2 text-sm text-text-secondary">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
              </svg>
              Click to expand
            </span>
          </div>
        </div>
      </button>
    );
  }

  return (
    <div className={`w-full max-w-4xl mx-auto ${className}`}>
      {title && (
        <h3 className="text-2xl font-semibold mb-4 text-text-primary">{title}</h3>
      )}
      {diagramContent}
    </div>
  );
}
